from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

import tempfile


def generate_pdf_report(analysis):

    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pdf"
    )

    doc = SimpleDocTemplate(temp_file.name)

    styles = getSampleStyleSheet()

    content = []

    title = Paragraph(
        "AI Resume & Job Match Analysis Report",
        styles["Title"]
    )

    content.append(title)

    content.append(Spacer(1, 12))

    subtitle = Paragraph(
        "Generated by Shubh Beniwal",
        styles["Heading3"]
    )

    content.append(subtitle)

    content.append(Spacer(1, 20))

    analysis_text = analysis.replace(
        "\n",
        "<br/>"
    )

    content.append(
        Paragraph(
            analysis_text,
            styles["BodyText"]
        )
    )

    doc.build(content)

    return temp_file.name